POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbmVjYXQiLCJpZCI6IjY3MmE1NjQ0YWZiMGJhYjdiZGNiMjc5ZCIsImlhdCI6MTczMDg4MzEzM30.i5ZXH-OX-wgPh5iP8vfkpLKN-e_AETuK1sdWHYW0Kzw

{
  "title": "Disc golf forte0",
  "author": "Rick Sanchez0",
  "url": "blog.dgf.net0",
  "likes": 1
}